### ISSUE TITLE
Change config so names generate off of repo name

### ISSUE THREAD

**Issue by awmatheson** [Azure/aml-template#21]
To minimize the lines of config and even eliminate configuration in some cases, we can auto generate the name using the environment variable in actions for the repo name and append some identifier.

## Example:

The workflow input could be:

```yaml
# Connect or Create the Azure Machine Learning Workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@master
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          ws_name:${{ GITHUB_REPOSITORY }}
```

and the resulting names would look something like:

- model name: `aml-template-model`
- compute name: `aml-template-compute`
- workspace name: `aml-template-workspace`
- deployment name: `aml-template-dev[prod]-aks`

The areas this needs to be addressed:

- [x] https://github.com/Azure/aml-deploy
- [x] https://github.com/Azure/aml-run
- [x] https://github.com/Azure/aml-compute
- [x] https://github.com/Azure/aml-workspace
- [x] https://github.com/Azure/aml-registermodel
